server:
  port: 7002
spring:
  application:
    name: cloud-eureka-server7001
eureka:
  instance:
    appname: eureka7002.com
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
#      defaultZone: http://${eureka.instance.appname}:${server.port}/eureka/
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka/