server:
  port: 7001
spring:
  application:
    name: cloud-eureka-server7001
eureka:
  instance:
    appname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://${eureka.instance.appname}:${server.port}/eureka/
      # 集群版
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
