server:
  port: 83
spring:
  application:
    name: cloudalibaba-consumer-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
service-url:
  nacos-user-service: http://cloudalibaba-provicer-payment